In [37]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler,MaxAbsScaler,RobustScaler,Normalizer

**Normalization is scaling technique in which values are shifted and rescaled ranging between 0 & 1 aka min/Max Scalar**

x' = x - Xmin / Xmax - Xmin

Standardisation is the technique 
when the values are centered around the mean with a unique standard deviation 

X' = x - mu/sigma


if our data is not normally distributed than we use normalization else we use normal distribution

In [9]:
df = pd.read_csv(r"https://raw.githubusercontent.com/selva86/datasets/refs/heads/master/BostonHousing.csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [10]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [13]:
scalar = MinMaxScaler()
# normalize the data 
normalized_data = scalar.fit_transform(df)

In [17]:
df2 = pd.DataFrame(normalized_data,columns=df.columns)
df2.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,0.040544,0.113636,0.391378,0.069170,0.349167,0.521869,0.676364,0.242381,0.371713,0.422208,0.622929,0.898568,0.301409,0.389618
std,0.096679,0.233225,0.251479,0.253994,0.238431,0.134627,0.289896,0.191482,0.378576,0.321636,0.230313,0.230205,0.197049,0.204380
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000851,0.000000,0.173387,0.000000,0.131687,0.445392,0.433831,0.088259,0.130435,0.175573,0.510638,0.945730,0.144040,0.267222
50%,0.002812,0.000000,0.338343,0.000000,0.314815,0.507281,0.768280,0.188949,0.173913,0.272901,0.686170,0.986232,0.265728,0.360000
75%,0.041258,0.125000,0.646628,0.000000,0.491770,0.586798,0.938980,0.369088,1.000000,0.914122,0.808511,0.998298,0.420116,0.444444
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
scalar = StandardScaler()
df_scaled = scalar.fit_transform(df)
df3 = pd.DataFrame(df_scaled,columns=df.columns)
df3

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,-0.419782,0.284830,-1.287909,-0.272599,-0.144217,0.413672,-0.120013,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.075562,0.159686
1,-0.417339,-0.487722,-0.593381,-0.272599,-0.740262,0.194274,0.367166,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.492439,-0.101524
2,-0.417342,-0.487722,-0.593381,-0.272599,-0.740262,1.282714,-0.265812,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.208727,1.324247
3,-0.416750,-0.487722,-1.306878,-0.272599,-0.835284,1.016303,-0.809889,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.361517,1.182758
4,-0.412482,-0.487722,-1.306878,-0.272599,-0.835284,1.228577,-0.511180,1.077737,-0.752922,-1.106115,0.113032,0.441052,-1.026501,1.487503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.413229,-0.487722,0.115738,-0.272599,0.158124,0.439316,0.018673,-0.625796,-0.982843,-0.803212,1.176466,0.387217,-0.418147,-0.014454
502,-0.415249,-0.487722,0.115738,-0.272599,0.158124,-0.234548,0.288933,-0.716639,-0.982843,-0.803212,1.176466,0.441052,-0.500850,-0.210362
503,-0.413447,-0.487722,0.115738,-0.272599,0.158124,0.984960,0.797449,-0.773684,-0.982843,-0.803212,1.176466,0.441052,-0.983048,0.148802
504,-0.407764,-0.487722,0.115738,-0.272599,0.158124,0.725672,0.736996,-0.668437,-0.982843,-0.803212,1.176466,0.403225,-0.865302,-0.057989
505,-0.415000,-0.487722,0.115738,-0.272599,0.158124,-0.362767,0.434732,-0.613246,-0.982843,-0.803212,1.176466,0.441052,-0.669058,-1.157248

In [23]:
# mean Normalization
df4 = (df - df.mean())/df.max() - df.min()
df4

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,-0.046861,0.066364,-0.778197,-0.06917,-0.404168,-3.527929,-2.933749,-1.105277,-1.356225,-187.157858,-12.743433,-0.218650,-1.932082,-4.970656
1,-0.046625,-0.113636,-0.606603,-0.06917,-0.483387,-3.545469,-2.796749,-1.032947,-1.314559,-187.233808,-12.629797,-0.218650,-1.822522,-5.018656
2,-0.046626,-0.113636,-0.606603,-0.06917,-0.483387,-3.458453,-2.974749,-1.032947,-1.314559,-187.233808,-12.629797,-0.228904,-1.957102,-4.756656
3,-0.046568,-0.113636,-0.782883,-0.06917,-0.496016,-3.479751,-3.127749,-0.942641,-1.272892,-187.261937,-12.588888,-0.224369,-1.985809,-4.782656
4,-0.046156,-0.113636,-0.782883,-0.06917,-0.496016,-3.462781,-3.043749,-0.942641,-1.272892,-187.261937,-12.588888,-0.218650,-1.922864,-4.726656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.046228,-0.113636,-0.431405,-0.06917,-0.363984,-3.525879,-2.894749,-1.238159,-1.356225,-187.190207,-12.484342,-0.231020,-1.808564,-5.002656
502,-0.046423,-0.113636,-0.431405,-0.06917,-0.363984,-3.579751,-2.818749,-1.253918,-1.356225,-187.190207,-12.484342,-0.218650,-1.824102,-5.038656
503,-0.046249,-0.113636,-0.431405,-0.06917,-0.363984,-3.482257,-2.675749,-1.263814,-1.356225,-187.190207,-12.484342,-0.218650,-1.914700,-4.972656
504,-0.045701,-0.113636,-0.431405,-0.06917,-0.363984,-3.502986,-2.692749,-1.245556,-1.356225,-187.190207,-12.484342,-0.227342,-1.892577,-5.010656
505,-0.046399,-0.113636,-0.431405,-0.06917,-0.363984,-3.590002,-2.777749,-1.235982,-1.356225,-187.190207,-12.484342,-0.218650,-1.855706,-5.212656

In [34]:
# maximum absolute scaling
df5 = MaxAbsScaler().fit_transform(df)
df5 = pd.DataFrame(df5,columns=df.columns)
df5

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.000071,0.18,0.083273,0.0,0.617681,0.748861,0.652,0.337278,0.041667,0.416315,0.695455,1.000000,0.131156,0.480
1,0.000307,0.00,0.254867,0.0,0.538462,0.731321,0.789,0.409607,0.083333,0.340366,0.809091,1.000000,0.240716,0.432
2,0.000307,0.00,0.254867,0.0,0.538462,0.818337,0.611,0.409607,0.083333,0.340366,0.809091,0.989746,0.106136,0.694
3,0.000364,0.00,0.078587,0.0,0.525832,0.797039,0.458,0.499913,0.125000,0.312236,0.850000,0.994281,0.077430,0.668
4,0.000776,0.00,0.078587,0.0,0.525832,0.814009,0.542,0.499913,0.125000,0.312236,0.850000,1.000000,0.140374,0.724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000704,0.00,0.430065,0.0,0.657865,0.750911,0.691,0.204395,0.041667,0.383966,0.954545,0.987629,0.254675,0.448
502,0.000509,0.00,0.430065,0.0,0.657865,0.697039,0.767,0.188636,0.041667,0.383966,0.954545,1.000000,0.239136,0.412
503,0.000683,0.00,0.430065,0.0,0.657865,0.794533,0.910,0.178741,0.041667,0.383966,0.954545,1.000000,0.148538,0.478
504,0.001232,0.00,0.430065,0.0,0.657865,0.773804,0.893,0.196998,0.041667,0.383966,0.954545,0.991308,0.170661,0.440
505,0.000533,0.00,0.430065,0.0,0.657865,0.686788,0.808,0.206572,0.041667,0.383966,0.954545,1.000000,0.207532,0.238

In [36]:
# median and quantile normalization scaling
# x - median(x) / iqr(x)
df6 = RobustScaler().fit_transform(df)
df6 = pd.DataFrame(df6,columns=df.columns)
df6

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,-0.069593,1.44,-0.571650,0.0,0.000000,0.496612,-0.250765,0.285777,-0.20,-0.087855,-1.339286,0.261902,-0.637681,0.351097
1,-0.063755,0.00,-0.202943,0.0,-0.394286,0.287940,0.028542,0.569789,-0.15,-0.227390,-0.446429,0.261902,-0.221889,0.050157
2,-0.063760,0.00,-0.202943,0.0,-0.394286,1.323171,-0.334353,0.569789,-0.15,-0.227390,-0.446429,0.066675,-0.732634,1.692790
3,-0.062347,0.00,-0.581720,0.0,-0.457143,1.069783,-0.646279,0.924391,-0.10,-0.279070,-0.125000,0.153016,-0.841579,1.529781
4,-0.052144,0.00,-0.581720,0.0,-0.457143,1.271680,-0.475025,0.924391,-0.10,-0.279070,-0.125000,0.261902,-0.602699,1.880878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.053930,0.00,0.173509,0.0,0.200000,0.521003,-0.171254,-0.236007,-0.20,-0.147287,0.696429,0.026382,-0.168916,0.150470
502,-0.058759,0.00,0.173509,0.0,0.200000,-0.119919,-0.016310,-0.297887,-0.20,-0.147287,0.696429,0.261902,-0.227886,-0.075235
503,-0.054450,0.00,0.173509,0.0,0.200000,1.039973,0.275229,-0.336744,-0.20,-0.147287,0.696429,0.261902,-0.571714,0.338558
504,-0.040867,0.00,0.173509,0.0,0.200000,0.793360,0.240571,-0.265053,-0.20,-0.147287,0.696429,0.096414,-0.487756,0.100313
505,-0.058164,0.00,0.173509,0.0,0.200000,-0.241870,0.067278,-0.227459,-0.20,-0.147287,0.696429,0.261902,-0.347826,-1.166144

In [41]:
# L2 regulization is also called as ridge regression it prevents overfitting problem by adding a penalty to the Loss function,
# this penalty discourages large cooeficients in the model.

# vector unit length scaling using L2 normalization 
df7 = Normalizer(norm = 'l2').fit_transform(df)
df7 = pd.DataFrame(df7,columns=df.columns)
df7

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.000013,0.035955,0.004614,0.0,0.001075,0.013134,0.130238,0.008170,0.001998,0.591265,0.030562,0.792814,0.009948,0.047940
1,0.000058,0.000000,0.014961,0.0,0.000992,0.013588,0.166966,0.010511,0.004232,0.512112,0.037668,0.839907,0.019342,0.045709
2,0.000058,0.000000,0.015133,0.0,0.001004,0.015379,0.130778,0.010632,0.004281,0.517974,0.038099,0.840809,0.008626,0.074272
3,0.000071,0.000000,0.004772,0.0,0.001003,0.015319,0.100257,0.013270,0.006567,0.485964,0.040935,0.863856,0.006436,0.073114
4,0.000150,0.000000,0.004740,0.0,0.000996,0.015539,0.117842,0.013181,0.006523,0.482675,0.040658,0.862945,0.011589,0.078707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000129,0.000000,0.024652,0.0,0.001184,0.013624,0.142789,0.005122,0.002066,0.564130,0.043395,0.810012,0.019982,0.046288
502,0.000093,0.000000,0.024399,0.0,0.001172,0.012517,0.156866,0.004678,0.002045,0.558335,0.042949,0.811733,0.018570,0.042131
503,0.000124,0.000000,0.024272,0.0,0.001166,0.014193,0.185144,0.004410,0.002035,0.555433,0.042726,0.807514,0.011475,0.048626
504,0.000224,0.000000,0.024430,0.0,0.001173,0.013913,0.182867,0.004892,0.002048,0.559045,0.043003,0.805701,0.013270,0.045051
505,0.000097,0.000000,0.024382,0.0,0.001171,0.012324,0.165133,0.005120,0.002044,0.557936,0.042918,0.811152,0.016105,0.024320